services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/nginx/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    ports:
      - "${APP_WEB_PORT}:80"
    volumes:
      - ./:${APP_PATH}
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    build:
      args:
        gid: ${GID}
        uid: ${UID}
      context: .
      dockerfile: ./docker/dockerfiles/php/Dockerfile
      target: dev
    container_name: ${COMPOSE_PROJECT_NAME}-php
    volumes:
      - ./:${APP_PATH}
      - ./docker/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/config/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - db
      - redis

  db:
    container_name: ${COMPOSE_PROJECT_NAME}-db
    build:
      context: .
      dockerfile: ./docker/dockerfiles/mysql/Dockerfile
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/config/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./docker/config/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "${APP_MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
      - MYSQL_DATABASE=${DB_DATABASE}

  redis:
    container_name: ${COMPOSE_PROJECT_NAME}-redis
    image: redis:7.0.11-alpine
    volumes:
      - redis-data:/data
    ports:
      - "${APP_REDIS_PORT}:6379"

  npm:
    build:
      context: .
      dockerfile: ./docker/dockerfiles/node/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}-npm
    volumes:
      - ./:${APP_PATH}:cached
      - ./.env:${APP_PATH}/.env
    working_dir: ${APP_PATH}
    profiles: ["npm"]
    entrypoint: ['npm']
    ports:
      - ${APP_VITE_PORT}:${APP_VITE_PORT}

  centrifugo:
    container_name: ${COMPOSE_PROJECT_NAME}-centrifugo
    image: centrifugo/centrifugo:v6.1.0
    volumes:
      - ./docker/config/centrifugo:/centrifugo
    command: centrifugo -c config.json
    ports:
      - "${CENTRIFUGO_CLIENT_PORT}:8000"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

#  scheduler:
#    container_name: ${COMPOSE_PROJECT_NAME}-scheduler
#    build:
#      args:
#        gid: ${GID}
#        uid: ${UID}
#      context: .
#      dockerfile: ./docker/dockerfiles/php/Dockerfile
#      target: scheduler
#    volumes:
#      - ./:${APP_PATH}
#      - ./docker/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
#      - ./docker/config/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
#    depends_on:
#      - php

  worker:
    container_name: ${COMPOSE_PROJECT_NAME}-worker
    build:
      args:
        gid: ${GID}
        uid: ${UID}
      context: .
      dockerfile: ./docker/dockerfiles/php/Dockerfile
      target: worker
    restart: on-failure
    volumes:
      - ./:${APP_PATH}
      - ./docker/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/config/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/config/php/supervisord.conf:/etc/supervisor/supervisord.conf
    depends_on:
      - php

volumes:
  db-data:
  redis-data: